  DOCKERHUB_REPOSITORY:  dfedigital/get-into-teaching-api
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           Get Into Teaching API Service
  PAAS_APPLICATION_NAME: get-into-teaching-api
  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/${{github.repository}}/master/.github/image.png?size=48
