  DOCKER_REPOSITORY:     ghcr.io/dfe-digital/get-into-teaching-api
  APPLICATION:           Get Into Teaching API Service
  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          Get Into Teaching API Service
  Sentry__Dsn:           ""       
# NB the Sentry__Dsn variable is case-sensitive
