paas_space                = "get-into-teaching"
monitor_space             = "get-into-teaching"
paas_database_common_name = "get-into-teaching-api-dev-pg-common-svc"
paas_redis_1_name         = "get-into-teaching-dev-redis-svc"
paas_api_application_name = "get-into-teaching-api-dev"
monitor_scrape_applications = [{ name : "get-into-teaching-api-dev", port : 8080 }, { name : "get-into-teaching-app-dev", port : 3000 }, { name : "get-teacher-training-adviser-service-dev", port : 3000 }]
application_instances = 1
monitoring            = 1
influx                = 1
environment           = "dev"
azure_key_vault       = "s146d01-kv"
azure_resource_group  = "s146d01-rg"
alerts                = {}
