paas_space="get-into-teaching-production"
paas_postgres_1_name="get-into-teaching-api-prod-pg1-svc"
paas_postgres_2_name="get-into-teaching-api-prod-pg2-svc"
paas_redis_1_name   ="get-into-teaching-api-prod-redis-svc"
paas_api_application_name="get-into-teaching-api-production"
paas_api_route_name="get-into-teaching-api-production"
paas_logging_endpoint_port="syslog-tls://89d7be0f-ddcd-437e-ad3c-c8125d0bad00-ls.logit.io:18190"
ASPNETCORE_ENVIRONMENT="Production"
