paas_space="get-into-teaching-test"
paas_postgres_1_name="get-into-teaching-api-test-pg1-svc"
paas_postgres_2_name="get-into-teaching-api-test-pg2-svc"
paas_redis_1_name   ="get-into-teaching-api-test-redis-svc"
paas_api_application_name="get-into-teaching-api-test"
paas_api_route_name="get-into-teaching-api-test"
paas_logging_endpoint_port="syslog-tls://89d7be0f-ddcd-437e-ad3c-c8125d0bad00-ls.logit.io:18190"

CRM_SERVICE_URL="https://gitis-dev.api.crm4.dynamics.com"
ASPNETCORE_ENVIRONMENT="Staging"
