{
 "title": "App Page Insights",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "category", "query": "performance,seo,accessibility" }
  ]
 },
 "panels": [
  { "title": "$category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "category" },
  {
   "title": "Avg Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Min Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Max Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Score per Page",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[$__interval])) by (path, strategy)"
    }
   ]
  },
  {
   "title": "Avg Score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[1d])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  { "title": "$category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Avg Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Min Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Max Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Score per Page",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[$__interval])) by (path, strategy)"
    }
   ]
  },
  {
   "title": "Avg Score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[1d])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  { "title": "$category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Avg Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Min Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Max Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(app_page_speed_score_$category[$__interval])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Score per Page",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[$__interval])) by (path, strategy)"
    }
   ]
  },
  {
   "title": "Avg Score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(app_page_speed_score_$category[1d])) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  }
 ]
}