{
 "title": "CF Overview",
 "description": "Cloud Foundry Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "OrgName",
    "label": "OrgName",
    "query": "label_values(memory_utilization, organisation)"
   },
   {
    "name": "SpaceName",
    "label": "SpaceName",
    "query": "label_values(memory_utilization{organisation =~\"$OrgName\"},space)"
   },
   {
    "name": "Applications",
    "label": "Applications",
    "query": "label_values(memory_utilization{space =~\"$SpaceName\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count( memory_utilization{space=\"$SpaceName\" , app=~\"$Applications\" , exported_instance=\"0\"})"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count(connections{ space=\"$SpaceName\" })"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (app) ( cpu{app=~\"$Applications\" , space=\"$SpaceName\"})",
     "legendFormat": "{{app}}|CPU"
    },
    {
     "expr": "sum by (app) ( memory_bytes{app=~\"$Applications\" , space=\"$SpaceName\"})",
     "legendFormat": "{{app}}|MEM"
    },
    {
     "expr": "sum by ( app ) ( disk_bytes{ space=\"$SpaceName\" , app=~\"$Applications\" })",
     "legendFormat": "{{app}}|DISK"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ( app ) ( disk_bytes{ space=\"$SpaceName\" , app=~\"$Applications\" })",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu{space=\"$SpaceName\" , app=~\"$Applications\" }",
     "legendFormat": "{{app}} Instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memory_utilization{space=\"$SpaceName\" , app=~\"$Applications\" }",
     "legendFormat": "{{app}}  Instance {{exported_instance}}"
    }
   ]
  }
 ]
}