{
 "title": "CSP Violations",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metric",
    "label": "Metric",
    "query": "app_csp_violations_total, tta_csp_violations_total"
   },
   {
    "name": "cf_app",
    "label": "Cloud Foundry App",
    "query": "get-into-teaching-app-prod, get-teacher-training-adviser-service-prod"
   }
  ]
 },
 "panels": [
  { "title": "$metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "metric" },
  {
   "title": "Total CSP Violations By Directive",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase($metric[$__range])) by (violated_directive)"
    }
   ]
  },
  {
   "title": "Total CSP Violations by Blocked URI",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase($metric[$__range])) by (blocked_uri) > 0"
    }
   ]
  },
  {
   "title": "Total CSP Violations by Document URI",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase($metric[$__range])) by (document_uri) > 0"
    }
   ]
  },
  {
   "title": "Google CSP Violations by Blocked URI",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(app_csp_violations_total{blocked_uri=~\".*google.*\"}[$__range])) by (blocked_uri) > 0"
    }
   ]
  },
  { "title": "$metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Total CSP Violations By Directive",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 42 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase($metric[$__range])) by (violated_directive)"
    }
   ]
  },
  {
   "title": "Total CSP Violations by Blocked URI",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase($metric[$__range])) by (blocked_uri) > 0"
    }
   ]
  },
  {
   "title": "Total CSP Violations by Document URI",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase($metric[$__range])) by (document_uri) > 0"
    }
   ]
  },
  { "title": "$cf_app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }, "repeat": "cf_app" },
  {
   "title": "Latest CSP Violations",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "\"csp-report\" AND cf.app:\"$cf_app\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "$cf_app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Latest CSP Violations",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "\"csp-report\" AND cf.app:\"$cf_app\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}