{
 "title": "Deployments",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total Deployments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:104", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "graph",
   "gridPos": { "h": 4, "w": 22, "x": 1, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:126",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:124",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "github.Action: Deploy",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:104", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:104", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : failure",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "options": {
    "content": "<h1 style=\"color: #5e9ca0;\"><span style=\"color: #00ccff;\">DEVELOPMENT</span></h1>\n"
   }
  },
  {
   "title": "Adviser",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Development AND github.Application: \"get-teacher-training-adviser-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Development AND github.Application: \"get-into-teaching-app\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Development AND github.Application: \"get-into-teaching-api\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "options": {
    "content": "<h1 style=\"color: #5e9ca0;\"><span style=\"color: #00ccff;\">REVIEW</span></h1>\n"
   }
  },
  {
   "title": "Adviser",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Review AND github.Application: \"get-teacher-training-adviser-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Review AND github.Application: \"get-into-teaching-app\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Review AND github.Application: \"get-into-teaching-api\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "options": {
    "content": "<h1 style=\"color: #5e9ca0;\"><span style=\"color: #00ccff;\">TEST</span></h1>\n"
   }
  },
  {
   "title": "Adviser",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Test AND github.Application: \"get-teacher-training-adviser-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Test AND github.Application: \"get-into-teaching-app\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Test AND github.Application: \"get-into-teaching-api\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "options": {
    "content": "<h1 style=\"color: #5e9ca0;\"><span style=\"color: #00ccff;\">PRODUCTION</span></h1>\n"
   }
  },
  {
   "title": "Adviser",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Production  AND github.Application: \"get-teacher-training-adviser-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Production AND github.Application: \"get-into-teaching-app\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "github.Action: Deploy AND github.Status : success AND github.Environment: Production AND github.Application: \"get-into-teaching-api\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}