{
 "title": "Get into Teaching API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CRM Sync Duration",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_crm_sync_duration_seconds_bucket[1d]))",
     "legendFormat": "95p"
    }
   ]
  },
  {
   "title": "Location Sync Duration",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 2, "x": 2, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_location_sync_duration_seconds_bucket[1d]))",
     "legendFormat": "95p"
    }
   ]
  },
  {
   "title": "Location Batch Duration",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 2, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_location_batch_duration_seconds_bucket[1d]))",
     "legendFormat": "96p"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "sum" }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connections", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Hangfire Jobs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_hangfire_jobs{state=~\"deleted|failed|enqueued|processing|retry|scheduled\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "Response Time by Action",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{controller=~\".+\",action=~\".+\",code=~\"2..\"} / http_request_duration_seconds_count{controller=~\".+\",action=~\".+\",code=~\"2..\"}",
     "legendFormat": "{{method}} - {{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"2..\"})",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"4..\"})",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"5..\"})",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"3..\"})",
     "legendFormat": "3xx"
    }
   ]
  }
 ]
}