{
 "title": "Get into Teaching API",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "CRM Sync Duration",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(api_crm_sync_duration_seconds_bucket[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connections", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Location Batch Duration",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_location_batch_duration_seconds_bucket[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"2..\"})",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"4..\"})",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"5..\"})",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"3..\"})",
     "legendFormat": "3xx"
    }
   ]
  },
  {
   "title": "Location Sync Duration",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(api_location_sync_duration_seconds_bucket[$__interval]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$__interval])) by (le) "
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Response Time by Action",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{controller=~\".+\",action=~\".+\",code=~\"2..\"} / http_request_duration_seconds_count{controller=~\".+\",action=~\".+\",code=~\"2..\"}",
     "legendFormat": "{{method}} - {{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Hangfire Jobs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_hangfire_jobs{state=~\"deleted|failed|enqueued|processing|retry|scheduled\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}