{
 "title": "Get into Teaching Apps",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "App",
    "label": "Elasticsearch App",
    "query": "get-into-teaching-app-prod,get-into-teaching-app-test,get-teacher-training-adviser-service-test,get-teacher-training-adviser-service-prod"
   },
   { "name": "Prefix", "label": "Prometheus App", "query": "app,tta" },
   {
    "name": "CFApp",
    "label": "Cloud Foundry App",
    "query": "get-into-teaching-app-prod,get-teacher-training-adviser-service-prod,get-into-teaching-app-test,get-teacher-training-adviser-service-test"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Rate by Path",
   "type": "graph",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(${Prefix}_requests_total{status !~ \"2\\\\d\\\\d|3\\\\d\\\\d|404\"}[3m])) by (path, status)",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Healthy",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"/healthcheck.json\" AND access.response_code:200 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Unavailable",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"/healthcheck.json\" AND access.response_code >=400 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu{app=\"$CFApp\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "memory_utilization{app=\"$CFApp\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total req/s",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(${Prefix}_requests_total[3m]))"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(${Prefix}_cache_read_total{hit=\"true\"}[$__range]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(increase(${Prefix}_cache_read_total{hit!=\"true\"}[$__range]))",
     "legendFormat": "Miss"
    },
    {}
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(${Prefix}_requests_total{path=~\".+\",status=~\"2..\"}[$__range]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(${Prefix}_requests_total{path=~\".+\",status!~\"[^4]..|404|429\"}[$__range]))",
     "legendFormat": "4xx (!404)"
    },
    {
     "expr": "sum(increase(${Prefix}_requests_total{path=~\".+\",status=~\"5..\"}[$__range]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(${Prefix}_requests_total{path=~\".+\",status=~\"3..\"}[$__range]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(${Prefix}_requests_total{path=~\".+\",status=~\"404\"}[$__range]))",
     "legendFormat": "404"
    },
    {
     "expr": "sum(increase(${Prefix}_requests_total{path=~\".+\",status=~\"429\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Response Time by Action",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(${Prefix}_request_duration_ms_sum{path=~\".+\",status=~\"2..\"}) by (method, path) / sum(${Prefix}_request_duration_ms_count{path=~\".+\",status=~\"2..\"}) by (method, path) ",
     "legendFormat": "{{method}} - {{path}}"
    },
    {}
   ]
  },
  {
   "title": "Response Time by Action",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(${Prefix}_render_view_ms_sum{identifier=~\".+\"}) by (identifier) / sum(${Prefix}_render_view_ms_count{identifier=~\".+\"}) by (identifier)",
     "legendFormat": "{{identifier}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(${Prefix}_request_duration_ms_bucket[$__interval])) by (le))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(${Prefix}_request_duration_ms_bucket[$__interval])) by (le))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(${Prefix}_request_duration_ms_bucket[$__interval])) by (le))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(${Prefix}_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(increase(${Prefix}_request_duration_ms_bucket[$__range])) by (le) "
    }
   ]
  }
 ]
}