{
 "title": "Get into Teaching Api - Event Search",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_count[$__interval]))"
    }
   ]
  },
  {
   "title": "Total by Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "No Type"
    },
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "Train to Teach"
    },
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",type_id=\"222750008\"}[$__interval]))",
     "legendFormat": "Online"
    },
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",type_id=\"222750009\"}[$__interval]))",
     "legendFormat": "School and University"
    }
   ]
  },
  {
   "title": "Total by Radius",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",radius!~\".+\"}[$__interval]))",
     "legendFormat": "No Radius"
    },
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",radius=\"100\"}[$__interval]))",
     "legendFormat": "100 miles"
    },
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",radius=\"50\"}[$__interval]))",
     "legendFormat": "50 miles"
    },
    {
     "expr": "sum(increase(api_teaching_event_search_results_count_bucket{le=\"+Inf\",radius=\"30\"}[$__interval]))",
     "legendFormat": "30 miles"
    }
   ]
  },
  {
   "title": "In-person Results by Radius (Train to Teach)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "No Radius",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"+Inf\",radius!~\".+\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius!~\".+\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "> 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius!~\".+\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius!~\".+\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "6 - 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius!~\".+\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius!~\".+\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "1 - 5"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius!~\".+\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "10 miles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"+Inf\",radius=\"10\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"10\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "> 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"10\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"10\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "6 - 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"10\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"10\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "1 - 5"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"10\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "25 miles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"+Inf\",radius=\"25\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"25\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "> 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"25\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"25\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "6 - 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"25\",type_id=\"222750001\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"25\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "1 - 5"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"25\",type_id=\"222750001\"}[$__interval]))",
     "legendFormat": "0"
    }
   ]
  },
  { "title": "In-person Results by Radius", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "No Radius",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"+Inf\",radius!~\".+\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius!~\".+\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "> 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius!~\".+\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius!~\".+\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "6 - 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius!~\".+\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius!~\".+\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "1 - 5"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius!~\".+\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "10 miles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"+Inf\",radius=\"10\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"10\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "> 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"10\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"10\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "6 - 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"10\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"10\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "1 - 5"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"10\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "25 miles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"+Inf\",radius=\"25\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"25\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "> 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"10\",radius=\"25\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"25\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "6 - 10"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"5\",radius=\"25\",type_id!~\".+\"}[$__interval])) - sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"25\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "1 - 5"
    },
    {
     "expr": "sum(increase(api_in_person_teaching_event_results_count_bucket{le=\"0.75\",radius=\"25\",type_id!~\".+\"}[$__interval]))",
     "legendFormat": "0"
    }
   ]
  }
 ]
}