{
 "title": "Get into Teaching API",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "App",
    "query": "get-into-teaching-api-prod,get-into-teaching-api-test"
   },
   {
    "name": "Space",
    "query": "get-into-teaching-production,get-into-teaching-test,get-into-teaching"
   }
  ]
 },
 "panels": [
  { "title": "Engagement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get an Adviser Sign Ups",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"TeacherTrainingAdviser - CandidatesController - Sign Up\" AND Client: \"Get an adviser\" AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Apply Adviser Sign Ups",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"TeacherTrainingAdviser - CandidatesController - Sign Up\" AND Client: \"Apply\" AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Teaching Event Sign Ups",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/teaching_events/attendees\" AND access.method: POST AND access.response_code: 204 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Callback Bookings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/get_into_teaching/callbacks\" AND access.method: POST AND access.response_code: 204 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "School Experience Sign Ups",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/schools_experience/candidates\" AND access.method: POST AND access.response_code: 204 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mailing List Sign Ups",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/mailing_list/members\" AND access.method: POST AND access.response_code: 204 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TOTPs Generated",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_generated_totps[$__range])) by (reference)",
     "legendFormat": "{{reference}}"
    }
   ]
  },
  {
   "title": "TOTP Failed Attempts",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_verified_totps{valid=\"False\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Magic Link Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Mailing List",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"/api/mailing_list/members/exchange_magic_link_token/\" AND access.method: GET AND access.response_code: 200 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Failed Attempt",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"/exchange_magic_link_token/\" AND access.method: GET AND access.response_code: 401 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Matchback Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Miss",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/candidates/access_tokens\" AND access.method: POST AND access.response_code: 404 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "TTA",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/teacher_training_adviser/candidates/exchange_access_token\" AND access.method: POST AND access.response_code: 200 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Mailing List",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/mailing_list/members/exchange_access_token\" AND access.method: POST AND access.response_code: 200 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Teaching Event",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "access.url:\"api/teaching_events/attendees/exchange_access_token\" AND access.method: POST AND access.response_code: 200 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TOTP Success Rates by Service",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(api_verified_totps{reference=\"teacher_training_adviser_wizard\"}[$__range])) by (reference) / sum(increase(api_generated_totps{reference=\"teacher_training_adviser_wizard\"}[$__range])) by (reference)) * 100",
     "legendFormat": "TTA"
    },
    {
     "expr": "(sum(increase(api_verified_totps{reference=\"Schools Experience\"}[$__range])) by (reference) / sum(increase(api_generated_totps{reference=\"Schools Experience\"}[$__range])) by (reference)) * 100",
     "legendFormat": "Schools Experience"
    }
   ]
  },
  {
   "title": "GiT TOTP Success Rates",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(api_verified_totps{reference=\"events_wizard-unverified\"}[$__range])) by (reference) / sum(increase(api_generated_totps{reference=\"events_wizard-unverified\"}[$__range])) by (reference)) * 100",
     "legendFormat": "Events (unverified)"
    },
    {
     "expr": "(sum(increase(api_verified_totps{reference=\"events_wizard\"}[$__range])) by (reference) / sum(increase(api_generated_totps{reference=\"events_wizard\"}[$__range])) by (reference)) * 100",
     "legendFormat": "Events"
    },
    {
     "expr": "(sum(increase(api_verified_totps{reference=\"mailing_list_wizard\"}[$__range])) by (reference) / sum(increase(api_generated_totps{reference=\"mailing_list_wizard\"}[$__range])) by (reference)) * 100",
     "legendFormat": "Mailing List"
    },
    {
     "expr": "(sum(increase(api_verified_totps{reference=\"callbacks_wizard\"}[$__range])) by (reference) / sum(increase(api_generated_totps{reference=\"callbacks_wizard\"}[$__range])) by (reference)) * 100",
     "legendFormat": "Callbacks"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Error Rate by Controller",
   "type": "graph",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code =~ \"5\\\\d\\\\d|400\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Healthy",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"api/operations/health_check\" AND \"healthy\" AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Degraded",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"api/operations/health_check\" AND \"degraded\" AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Unhealthy",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"api/operations/health_check\" AND \"unhealthy\" AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Unavailable",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"api/operations/health_check\"  AND access.response_code >=400 AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_percent{space=\"$Space\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connections{space=\"$Space\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Requests in Progress",
   "type": "stat",
   "description": "Across ALL controllers globally!",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_in_progress)" }
   ]
  },
  {
   "title": "Total req/s",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[3m]))"
    }
   ]
  },
  {
   "title": "CRM Sync Duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(api_crm_sync_duration_seconds_sum[$__range]) / rate(api_crm_sync_duration_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "CRM Sync Duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(api_crm_sync_duration_seconds_sum[$__range]) / rate(api_crm_sync_duration_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "Magic Link Token Generation Duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(api_magic_link_token_generation_duration_seconds_sum[$__range]) / rate(api_magic_link_token_generation_duration_seconds_count[$__range]) > 0)"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 87 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(api_cache_lookups{outcome=\"hit\"}[$__range]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(increase(api_cache_lookups{outcome=\"miss\"}[$__range]))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 87 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"2..\"}[$__range]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(http_requests_received_total{controller=~\".+\",action=~\".+\",code!~\"[^4]..|404\"}[$__range]))",
     "legendFormat": "4xx (!404)"
    },
    {
     "expr": "sum(increase(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"5..\"}[$__range]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"3..\"}[$__range]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(http_requests_received_total{controller=~\".+\",action=~\".+\",code=~\"404\"}[$__range]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Response Time by Action",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{controller=~\".+\",action=~\".+\",code=~\"2..\"}) by (method, controller, action) / sum(http_request_duration_seconds_count{controller=~\".+\",action=~\".+\",code=~\"2..\"}) by (method, controller, action) ",
     "legendFormat": "{{method}} - {{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$__interval])) by (le) "
    }
   ]
  },
  {
   "title": "Requests Received by Controller",
   "type": "graph",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Rate Limited Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "/candidates/access_tokens",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"/api/candidates/access_tokens\" AND access.method:\"POST\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/teaching_events/attendees",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"/api/teaching_events/attendees\" AND access.method:\"POST\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/mailing_list/members",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"/api/mailing_list/members\" AND access.method:\"POST\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "/teacher_training_adviser/candidates",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"/api/teacher_training_adviser/candidates\" AND access.method:\"POST\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Job Time Spent in Queue",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(api_hangfire_job_queue_duration_seconds_bucket[1h])) by (le, exported_job))",
     "legendFormat": "100p - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_hangfire_job_queue_duration_seconds_bucket[1h])) by (le, exported_job))",
     "legendFormat": "99p - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(api_hangfire_job_queue_duration_seconds_bucket[1h])) by (le, exported_job))",
     "legendFormat": "98p - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_hangfire_job_queue_duration_seconds_bucket[1h])) by (le, exported_job))",
     "legendFormat": "95p - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(api_hangfire_job_queue_duration_seconds_bucket[1h])) by (le, exported_job))",
     "legendFormat": "75p - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(api_hangfire_job_queue_duration_seconds_bucket[1h])) by (le, exported_job))",
     "legendFormat": "50p - {{exported_job}}"
    }
   ]
  },
  {
   "title": "Hangfire Jobs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_hangfire_jobs{state=~\"succeeded|deleted|failed|enqueued|processing|retry|scheduled\"}[10m]) ",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "External", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Google API Calls",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_google_api_calls[$__interval]))"
    }
   ]
  },
  {
   "title": "Notify Service API Calls",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"NotifyService - Sending Email\" AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Rate by External Provider",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 146 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "NotifyService",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"NotifyService - Failed to send email\" AND cf.app:\"$App\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "sum(rate(api_google_api_calls{result != \"success\"}[3m])) by (result)",
     "legendFormat": "Google Geocoder - {{result}}"
    }
   ]
  }
 ]
}