{
 "title": "HTTP Errors",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Space", "query": "label_values(space)" },
   {
    "name": "Application",
    "query": "label_values(memory_utilization{space =~\"$Space\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Client Errors",
     "bucketAggs": [
      {
       "$$hashKey": "object:62",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:128",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\" AND access.response_code: [400 TO 499]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Server Errors",
     "bucketAggs": [
      {
       "$$hashKey": "object:1257",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1255", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\" AND access.response_code: [500 TO 599]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Responses",
     "bucketAggs": [
      {
       "$$hashKey": "object:1275",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1273", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:755",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:753", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Client Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:755",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:753", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\" AND access.response_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Server Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:755",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:753", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\" AND access.response_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total. 404's ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:755",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:753", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\" AND access.response_code:404",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:128",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\" AND access.response_code: [400 TO 499]",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1308",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1306", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "cf.space: \"$Space\" AND cf.app:\"$Application\" AND access.response_code: [500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}