{
 "title": "Logs",
 "description": "Logit.io Logs",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Applications",
    "query": "label_values(memory_utilization{space =~\"$SpaceName\"},app)"
   },
   { "name": "SpaceName", "label": "SpaceName", "query": "label_values(space)" },
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Error Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:481",
       "fake": true,
       "field": "syslog_severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:450",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:448", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Rate Information",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:682",
       "fake": true,
       "field": "syslog_severity.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:670",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:668", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:832",
       "field": "@timestamp",
       "id": "2",
       "settings": {},
       "type": "log"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:830",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}