{
 "title": "Users against Resources",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests{space=\"get-into-teaching-production\",app=\"get-into-teaching-api-prod\"}[5m])) by (app) *60",
     "legendFormat": "API"
    },
    {
     "expr": "sum(rate(requests{space=\"get-into-teaching-production\",app=\"get-into-teaching-app-prod\"}[5m])) by (app) *60",
     "legendFormat": "APP"
    },
    {
     "expr": "sum(rate(requests{space=\"get-into-teaching-production\",app=\"get-teacher-training-adviser-service-prod\"}[5m])) by (app) *60",
     "legendFormat": "TTA"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ( exported_instance ) (memory_utilization{app=\"get-into-teaching-api-prod\"})",
     "legendFormat": "API {{exported_instance}}"
    },
    {
     "expr": "sum by ( exported_instance ) (memory_utilization{app=\"get-into-teaching-app-prod\"})",
     "legendFormat": "APP {{exported_instance}}"
    },
    {
     "expr": "sum by ( exported_instance ) (memory_utilization{app=\"get-teacher-training-adviser-service-prod\"})",
     "legendFormat": "TTA {{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_percent{service=\"get-into-teaching-api-prod-pg-common-svc\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "sum by ( exported_instance ) (cpu{app=\"get-into-teaching-api-prod\"} )",
     "legendFormat": "API  {{exported_instance}}"
    },
    {
     "expr": "sum by ( exported_instance ) (cpu{app=\"get-into-teaching-app-prod\"} )",
     "legendFormat": "APP  {{exported_instance}}"
    },
    {
     "expr": "sum by ( exported_instance ) (cpu{app=\"get-teacher-training-adviser-service-prod\"} )",
     "legendFormat": "TTA  {{exported_instance}}"
    }
   ]
  },
  {
   "title": "REDIS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "Redis Memory" }
   ]
  },
  {
   "title": "REDIS Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100 * ( redis_memory_used_bytes / redis_memory_max_bytes )"
    }
   ]
  },
  {
   "title": "Event Log",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1356",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1354",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "spreadsheet": "1dHwPqEsJbr6BlXLS5qE9_ia6JdsEZJ719yJNHlLAzZE"
    },
    {
     "cacheDurationSeconds": 300,
     "spreadsheet": "1dHwPqEsJbr6BlXLS5qE9_ia6JdsEZJ719yJNHlLAzZE"
    }
   ]
  }
 ]
}