title: Get Into Teaching API
author: Steven Fawcett
email: steve.fawcett@digital.education.gov.uk
description: Documentation for the Get Into Teaching API

remote_theme: frankieroberto/govuk-jekyll-theme
markdown: kramdown
