name: Build 
on:
  repository_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master

jobs:
  turnstyle:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: Development
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1
        id:   azSecret
        with:
            keyvault: ${{ secrets.KEY_VAULT}}
            secrets: 'ACTIONS-API-ACCESS_TOKEN, SLACK-WEBHOOK'

      - name: Check workflow concurrency
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 20
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification
        if: failure() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_COLOR:   ${{env.SLACK_FAILURE}}
           SLACK_MESSAGE: Content Delivery has failed. This is due to a workflow concurrency issue
           SLACK_TITLE:   Turnstyle failure ${{ github.workflow }}
           SLACK_WEBHOOK: steps.azSecret.outputs.SLACK-WEBHOOK

  build:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    needs: turnstyle 
    environment: Development
    outputs:
       image: ${{steps.docker_image.outputs.IMAGE}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1
        id:   azSecret
        with:
            keyvault: ${{ secrets.KEY_VAULT}}
            secrets: 'ACTIONS-API-ACCESS_TOKEN, SLACK-WEBHOOK, DOCKER-USERNAME, DOCKER-PASSWORD'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Get Short SHA
        id: vars
        run: |
             echo ::set-output name=sha_short::$(echo $GITHUB_SHA | cut -c -7)

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
             ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ steps.azSecret.outputs.DOCKER-USERNAME }}
          password: ${{ steps.azSecret.outputs.DOCKER-PASSWORD }}


      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
                 ${{env.DOCKERHUB_REPOSITORY}}:sha-${{ steps.vars.outputs.sha_short }}
          build-args: GIT_COMMIT_SHA=${{ steps.vars.outputs.sha_short }}

      - name: Slack Notification
        if: failure() && github.ref == 'refs/heads/master'
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_COLOR:   ${{env.SLACK_FAILURE}}
           SLACK_MESSAGE: 'The pipeline has failed to build the API image'
           SLACK_TITLE:   'Failure to Build API '
           SLACK_WEBHOOK: steps.azSecret.outputs.SLACK-WEBHOOK

  development:
    name: Development Deployment
    environment: Development
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{steps.tag_version.outputs.pr_number}}
      release_sha: ${{github.sha}}
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: set-up-environment
         uses: DFE-Digital/github-actions/set-up-environment@master

       - uses: Azure/login@v1
         with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

       - uses: Azure/get-keyvault-secrets@v1
         id:   azSecret
         with:
            keyvault: ${{ secrets.KEY_VAULT}}
            secrets: 'ACTIONS-API-ACCESS_TOKEN'

       - name: Trigger Development Deployment
         uses: benc-uk/workflow-dispatch@v1.1
         with:
           workflow: Deploy to PaaS
           token: steps.azSecret.outputs.ACTIONS-API-ACCESS_TOKEN
           inputs: '{"environment": "Development", "sha": "${{ github.sha }}"}'
           ref: ${{github.ref}}

       - name: Wait for Deployment to Development
         uses: fountainhead/action-wait-for-check@v1.0.0
         id: wait-for-deploy
         with:
           token: steps.azSecret.outputs.ACTIONS-API-ACCESS_TOKEN
           checkName: Deploy Development
           ref: ${{github.ref}}

       - name: Check if Development Deployment has returned with a failure
         if: steps.wait-for-deploy.outputs.conclusion == 'failure'
         run: exit 1

       - name: Trigger Development Fix Network Policies
         uses: benc-uk/workflow-dispatch@v1.1
         with:
           workflow: Fix Network policies 
           token: steps.azSecret.outputs.ACTIONS-API-ACCESS_TOKEN
           inputs: '{"environment": "Development" }'
           ref: ${{github.ref}}
        
       - name: Generate Tag from PR Number
         id:   tag_version
         uses: DFE-Digital/github-actions/GenerateReleaseFromSHA@master
         with:
           sha: ${{github.sha}}
          
       - name: Create a GitHub Release
         id: release
         if:   steps.tag_version.outputs.pr_found == 1
         uses: actions/create-release@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            tag_name: ${{ steps.tag_version.outputs.pr_number }}
            release_name: Release ${{ steps.tag_version.outputs.pr_number }}
            commitish: ${{github.sha}}
            prerelease: false
            draft:      false

       - name: Copy PR Info to Release
         if: steps.release.outputs.id      
         uses: DFE-Digital/github-actions/CopyPRtoRelease@master
         with:
           PR_NUMBER:  ${{ steps.tag_version.outputs.pr_number }}
           RELEASE_ID: ${{ steps.release.outputs.id }}
           TOKEN: ${{secrets.GITHUB_TOKEN}} 
           
           
  qa:
    name: Quality Assurance Deployment
    needs: development
    environment: Test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: set-up-environment
         uses: DFE-Digital/github-actions/set-up-environment@master

       - uses: Azure/login@v1
         with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

       - uses: Azure/get-keyvault-secrets@v1
         id:   azSecret
         with:
            keyvault: ${{ secrets.KEY_VAULT}}
            secrets: 'ACTIONS-API-ACCESS_TOKEN, SLACK-WEBHOOK'

       - name: Trigger Deployment to QA
         uses: benc-uk/workflow-dispatch@v1.1
         with:
           workflow: Deploy to PaaS
           token: steps.azSecret.outputs.ACTIONS-API-ACCESS_TOKEN
           inputs: '{"environment": "Test", "sha": "${{ github.sha }}" }'
           ref: ${{github.ref}}

       - name: Wait for Deployment to QA
         uses: fountainhead/action-wait-for-check@v1.0.0
         id: wait-for-deploy
         with:
           token: steps.azSecret.outputs.ACTIONS-API-ACCESS_TOKEN
           checkName: Deploy Test
           ref: ${{github.ref}}

       - name: Check if QA Deployment has returned with a failure
         if: steps.wait-for-deploy.outputs.conclusion == 'failure'
         run: exit 1

       - name: Slack Notification
         if: failure()
         uses: rtCamp/action-slack-notify@master
         env:
           SLACK_COLOR:   ${{env.SLACK_FAILURE}}
           SLACK_TITLE:   Failure in Post-Development Deploy
           SLACK_MESSAGE: Failure with initialising QA deployment for ${{env.APPLICATION}}
           SLACK_WEBHOOK: steps.azSecret.outputs.SLACK-WEBHOOK

  cypress:
    name: Run Cypress Tests on QA
    runs-on: ubuntu-latest
    environment: Test
    needs: qa
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: set-up-environment
         uses: DFE-Digital/github-actions/set-up-environment@master

       - uses: Azure/login@v1
         with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

       - uses: Azure/get-keyvault-secrets@v1
         id:   azSecret
         with:
            keyvault: ${{ secrets.KEY_VAULT}}
            secrets: 'ACTIONS-API-ACCESS_TOKEN'

       - name: Trigger Cypress Tests (DFE-Digital/get-into-teaching-frontend-tests )
         uses: benc-uk/workflow-dispatch@v1.1
         with:
           repo: DFE-Digital/get-into-teaching-frontend-tests
           workflow: Cypress
           token: steps.azSecret.outputs.ACTIONS-API-ACCESS_TOKEN
           inputs: '{"application": "BOTH" , "reference": "${{ github.sha }}" }'
           ref:  refs/heads/master

  production:
    name: Production Deployment
    runs-on: ubuntu-latest
    needs: [ cypress , development ]
    environment: Production
    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: set-up-environment
         uses: DFE-Digital/github-actions/set-up-environment@master

       - uses: Azure/login@v1
         with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

       - uses: Azure/get-keyvault-secrets@v1
         id:   azSecret
         with:
            keyvault: ${{ secrets.KEY_VAULT}}
            secrets: 'ACTIONS-API-ACCESS_TOKEN'

       - name: Get Release Id from Tag
         id: tag_id
         uses: DFE-Digital/github-actions/DraftReleaseByTag@master
         with:
           TAG: ${{needs.development.outputs.release_tag}}
           TOKEN: steps.azSecret.outputs.ACTIONS-API-ACCESS_TOKEN

       - name: Publish Release  
         if: steps.tag_id.outputs.release_id
         uses: eregon/publish-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           release_id: ${{steps.tag_id.outputs.release_id}}
