name: Run CVE scanner 
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  cve:
    name: CVE scanner 
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1
        id:   azSecret
        with:
           keyvault: ${{ secrets.KEY_VAULT}}
           secrets: 'SLACK-WEBHOOK'

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Scan image
        uses: anchore/scan-action@v2
        with:
             image:  localbuild/testimage:latest
             fail-build: true
             severity-cutoff: high
             acs-report-enable: true

      - name: upload Anchore scan SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_COLOR:    ${{ env.SLACK_FAILURE }}
           SLACK_MESSAGE:  'Pipeline Failure running CVE scanner for API'
           SLACK_TITLE:    'Failure: Running CVE Scanner'
           SLACK_WEBHOOK:  ${{ steps.azSecret.outputs.SLACK-WEBHOOK }}
