name: Run CVE scanner 
on:
  workflow_dispatch:

jobs:
  cve:
    name: CVE scanner 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - name: Install Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli  
