name: Fix Network policies 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to fix
        required: true
        default: Development
        type: environment

jobs:
  cf:
    name: Cloud Foundry Network
    runs-on: ubuntu-latest
    environment:
       name: ${{ github.event.inputs.environment }}
    concurrency: ${{github.event.inputs.environment}}
    steps:
      - name: Install Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli  
          
      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DfE-Digital/keyvault-yaml-secret@v1
        id:  keyvault-yaml-secret
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          secret: INFRA-KEYS
          key: PAAS-USERNAME,PAAS-PASSWORD 

      - name: Login to Cloud Foundry
        run: cf login -a api.london.cloud.service.gov.uk -u ${{ steps.keyvault-yaml-secret.outputs.PAAS-USERNAME}} -p ${{ steps.keyvault-yaml-secret.outputs.PAAS-PASSWORD}} -s get-into-teaching
             
      - name: Fix Development Policies 
        if:   github.event.inputs.environment == 'Development'
        run:  |
            cf target -s get-into-teaching
            cf add-network-policy prometheus-dev-get-into-teaching  get-into-teaching-api-dev --protocol tcp --port 8080
            cf add-network-policy prometheus-dev-get-into-teaching  get-into-teaching-app-dev --protocol tcp --port 3000
            cf add-network-policy prometheus-dev-get-into-teaching  get-teacher-training-adviser-service-dev  --protocol tcp --port 3000

      - name: Fix Test Policies 
        if:   github.event.inputs.environment == 'Test'
        run:  |
            cf target -s get-into-teaching-monitoring
            cf add-network-policy prometheus-prod-get-into-teaching  get-into-teaching-api-test -s get-into-teaching-test --protocol tcp --port 8080
            cf add-network-policy prometheus-prod-get-into-teaching  get-into-teaching-app-test -s get-into-teaching-test --protocol tcp --port 3000
            cf add-network-policy prometheus-prod-get-into-teaching  get-teacher-training-adviser-service-test -s get-into-teaching-test --protocol tcp --port 3000
            cf add-network-policy prometheus-prod-get-into-teaching  get-into-teaching-app-pagespeed -s get-into-teaching-test --protocol tcp --port 3000

      - name: Fix Production Policies 
        if:   github.event.inputs.environment == 'Production'
        run:  |
            cf target -s get-into-teaching-monitoring
            cf add-network-policy prometheus-prod-get-into-teaching  get-into-teaching-api-prod -s get-into-teaching-production --protocol tcp --port 8080
            cf add-network-policy prometheus-prod-get-into-teaching  get-into-teaching-app-prod -s get-into-teaching-production --protocol tcp --port 3000
            cf add-network-policy prometheus-prod-get-into-teaching  get-teacher-training-adviser-service-prod -s get-into-teaching-production --protocol tcp --port 3000

