---
name: Manual Release
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to release to
        required: true
        type: environment
      tag:
        description: Release Tag
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  manual:
    name: Deploy to ${{github.event.inputs.environment}}
    runs-on: ubuntu-latest
    environment:
      name: ${{github.event.inputs.environment}}
      url: ${{ steps.deploy.outputs.deploy-url }}
    concurrency: ${{github.event.inputs.environment}}
    defaults:
      run:
        shell: bash
    steps:
       - name: Checkout
         uses: actions/checkout@v6

       - name: set-up-environment
         uses: DFE-Digital/github-actions/set-up-environment@master

       - name: Get Release Id from Tag
         id: tag_id
         uses: DFE-Digital/github-actions/DraftReleaseByTag@master
         with:
           TAG: ${{ github.event.inputs.tag }}
           TOKEN: ${{ secrets.GITHUB_TOKEN }}

       - name: Check if found
         if:  steps.tag_id.outputs.release_id == ''
         run: |
              echo "::error ::Tag ${{ github.event.inputs.tag }} cannot be found in releases"
              exit 1

       - name: Get Short SHA
         id: vars
         run: |
           echo "image_tag_sha=sha-$(echo ${{steps.tag_id.outputs.release_sha}} | cut -c -7)" >> $GITHUB_OUTPUT

       - name: Trigger Deployment to ${{github.event.inputs.environment}}
         uses: ./.github/workflows/actions/deploy_v2
         id: deploy
         with:
           environment: "${{github.event.inputs.environment}}"
           sha:  "${{ steps.vars.outputs.image_tag_sha }}"
           azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
           azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

       - name: Teams Release Notification
         if: steps.tag_id.outputs.release_id && github.event.inputs.environment == 'production'
         uses: DFE-Digital/github-actions/send-to-teams-channel@master
         with:
           teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
           title: "Release Published to production: ${{steps.tag_id.outputs.release_name}}"
           service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
           minimal: true
           status: good
           message: |
             ${{ fromJson( steps.tag_id.outputs.release_body) }}

       - name: Notify teams channel on job failure
         if: failure()
         uses: DFE-Digital/github-actions/send-to-teams-channel@master
         with:
           teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
           title: Manual Deploy
           service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
           message: |
             Failure deploying ${{github.event.inputs.environment}}  release
