---  
name: Release Monitoring
on: 
  workflow_dispatch:

jobs:
  deploy_monitoring:
    name: 'Deploy Monitoring'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

       - name: Checkout
         uses: actions/checkout@v2
   
       - uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: 0.12.29
      
       - name: Terraform Init
         run: |
             cd terraform/monitoring && pwd
             terraform init -backend-config=dev.bk.vars
         env:
             ARM_ACCESS_KEY:           "${{ secrets.DEV_ARM_ACCESS_KEY  }}"
             TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME   }}"
             TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD   }}"
   
       - name: Terraform Plan
         run: |
             cd terraform/monitoring && pwd
             terraform plan -var-file=dev.env.tfvars -out plan
         env:
             ARM_ACCESS_KEY:           "${{ secrets.DEV_ARM_ACCESS_KEY  }}"
             TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME   }}"
             TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD   }}"
   
       - name: Terraform Apply
         run: |
             cd terraform/monitoring && pwd
             terraform apply -auto-approve plan
         env:
             ARM_ACCESS_KEY:           "${{ secrets.DEV_ARM_ACCESS_KEY  }}"

       - name: Slack Notification
         if: failure()
         uses: rtCamp/action-slack-notify@master
         env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_MESSAGE: ':disappointed_relieved: Pipeline Failure carrying out job ${{github.job}} :disappointed_relieved:'
           SLACK_TITLE: 'Failure: ${{ github.workflow }}'
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
               
