name: Publish Release Notes
on:
  release:
    types: [published]
    
env:
  APPLICATION:           Get Into Teaching API

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_COLOR:   ${{env.SLACK_SUCCESS}}
           SLACK_TITLE:   Release Published ${{github.event.release.name}}
           SLACK_MESSAGE: ${{github.event.release.body}}
           SLACK_WEBHOOK: ${{secrets.SLACK_RELEASE_NOTE_WEBHOOK}}
           MSG_MINIMAL:   true
