name: Link Trello card
on:
  pull_request:
    types: [ opened , edited]

permissions:
  contents: write
  id-token: write

jobs:
  attach-to-trello:
    name: Link Trello card to this PR
    if: "!contains( 'dependabot[bot] snyk-bot' , github.actor )"
    runs-on: ubuntu-latest
    steps:
      - name: Add Trello Comment
        uses: DFE-Digital/github-actions/AddTrelloComment@master
        with:
          MESSAGE:      ${{ github.event.pull_request.html_url }}
          CARD:         ${{ github.event.pull_request.body }}
          TRELLO-KEY:   ${{ secrets.TRELLO_KEY }}
          TRELLO-TOKEN: ${{ secrets.TRELLO_TOKEN }}
