name: Link Trello card
on:
  pull_request:
    types: [ opened , edited]

jobs:
  attach-to-trello:
    name: Link Trello card to this PR
    if: "!contains( 'dependabot[bot] snyk-bot' , github.actor )"
    runs-on: ubuntu-latest
    environment: development_aks
    steps:
      - uses: Azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch secrets from key vault
        uses: azure/CLI@v1
        id: fetch-secrets
        with:
          inlineScript: |
            SECRET_VALUE=$(az keyvault secret show --name "SLACK-WEBHOOK" --vault-name "${{ secrets.INFRA_KEY_VAULT}}" --query "value" -o tsv)
            echo "::add-mask::$SECRET_VALUE"
            echo "SLACK-WEBHOOK=$SECRET_VALUE" >> $GITHUB_OUTPUT
            SECRET_VALUE=$(az keyvault secret show --name "TRELLO-TOKEN" --vault-name "${{ secrets.INFRA_KEY_VAULT}}" --query "value" -o tsv)
            echo "::add-mask::$SECRET_VALUE"
            echo "TRELLO-TOKEN=$SECRET_VALUE" >> $GITHUB_OUTPUT

      - name: Add Trello Comment
        uses: DFE-Digital/github-actions/AddTrelloComment@master
        with:
          MESSAGE:      ${{ github.event.pull_request.html_url }}
          CARD:         ${{ github.event.pull_request.body }}
          TRELLO-KEY:   ${{ steps.fetch-secrets.outputs.TRELLO-KEY }}
          TRELLO-TOKEN: ${{ steps.fetch-secrets.outputs.TRELLO-TOKEN }}
