name: Link Trello card
on:
  pull_request:
    types: [ opened , edited]

jobs:
  attach-to-trello:
    name: Link Trello card to this PR
    if: "!contains( 'dependabot[bot] snyk-bot' , github.actor )"  
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DfE-Digital/keyvault-yaml-secret@v1
        id:  keyvault-yaml-secret
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          secret: INFRA-KEYS
          key: TRELLO-KEY , TRELLO-TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Add Trello Comment
        uses: DFE-Digital/github-actions/AddTrelloComment@master
        with:
          MESSAGE:      ${{ github.event.pull_request.html_url }} 
          CARD:         ${{ github.event.pull_request.body }}           
          TRELLO-KEY:   ${{ steps.keyvault-yaml-secret.outputs.TRELLO-KEY }}
          TRELLO-TOKEN: ${{ steps.keyvault-yaml-secret.outputs.TRELLO-TOKEN }}
